version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "cron"
      cronjob: "0 10 * * *"
      timezone: "Etc/GMT-8"
    open-pull-requests-limit: 100
    assignees:
      - rawvoid

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "cron"
      cronjob: "0 10 * * *"
      timezone: "Etc/GMT-8"
    open-pull-requests-limit: 100
    assignees:
      - rawvoid
