#!/bin/sh
set -eu

DEFAULTS_FILE="${DEFAULTS_FILE:-${defaultsFile}}"

if [ -r "${DEFAULTS_FILE}" ]; then
    while read -r line || [ -n "$line" ]; do
        line="${line#export }"
        case "$line" in
            \#* | \;* | "" ) continue ;;
            *=* )
                key="${line%%=*}"
                val="${line#*=}"
                case "$val" in
                    \"*\" | \'*\' )
                        val="${val#?}"
                        val="${val%?}"
                        ;;
                esac
                export "${key}=${val}"
                ;;
            * )
                echo "Error: Invalid line in ${DEFAULTS_FILE} (missing '='): '${line}'" >&2
                exit 1
                ;;
        esac
    done < "${DEFAULTS_FILE}"
fi
